/**
 * LLM Provider Interface
 */
export interface LLMProvider {
  name: string
  generate(prompt: string, options?: GenerationOptions): Promise<LLMResponse>
  chat(messages: Array<Message>, options?: GenerationOptions): Promise<LLMResponse>
}

export interface Message {
  role: 'system' | 'user' | 'assistant'
  content: string
}

export interface GenerationOptions {
  temperature?: number
  maxTokens?: number
  topP?: number
  frequencyPenalty?: number
  presencePenalty?: number
  stopSequences?: Array<string>
}

export interface LLMResponse {
  content: string
  usage?: {
    promptTokens: number
    completionTokens: number
    totalTokens: number
  }
  finishReason?: 'stop' | 'length' | 'content_filter'
}

/**
 * Prompt Templates
 */
export class PromptTemplate {
  private template: string
  private variables: Set<string>

  constructor(template: string) {
    this.template = template
    this.variables = new Set(
      template.match(/\{\{(\w+)\}\}/g)?.map(m => m.slice(2, -2)) || []
    )
  }

  format(values: Record<string, string>): string {
    let result = this.template
    
    for (const variable of this.variables) {
      const value = values[variable]
      if (!value) {
        throw new Error(`Missing required variable: ${variable}`)
      }
      result = result.replace(new RegExp(`\\{\\{${variable}\\}\\}`, 'g'), value)
    }
    
    return result
  }
}

/**
 * Prompt Template Library
 */
export const PROMPT_TEMPLATES = {
  analyzeCV: new PromptTemplate(`You are an expert resume reviewer. Analyze the following CV and provide constructive feedback.

CV Data:
{{cvData}}

Provide feedback on:
1. Overall strengths
2. Areas for improvement
3. Missing information
4. Suggestions for better impact`),

  generateSummary: new PromptTemplate(`You are a professional resume writer. Create a compelling {{wordCount}}-word professional summary.

Candidate Information:
- Current Role: {{currentRole}}
- Target Role: {{targetRole}}
- Key Skills: {{skills}}
- Years of Experience: {{yearsExperience}}

Write a professional summary that highlights their value proposition.`),

  improveAchievement: new PromptTemplate(`You are a career coach specializing in achievement statements. Improve the following bullet point to be more impactful and results-oriented.

Original: {{achievement}}
Role: {{role}}
Industry: {{industry}}

Rewrite using the STAR method (Situation, Task, Action, Result) and include quantifiable metrics where possible.`),

  optimizeATS: new PromptTemplate(`You are an ATS optimization expert. Compare the CV with the job description and identify missing keywords.

Job Description Keywords:
{{jobKeywords}}

CV Content:
{{cvContent}}

List the top 10 most important missing keywords and suggest where to add them in the CV.`),
}

/**
 * Base LLM Service - Abstracts provider implementation
 */
export abstract class BaseLLMService implements LLMProvider {
  abstract readonly name: string
  protected apiKey: string
  protected baseUrl: string

  constructor(apiKey: string, baseUrl: string) {
    this.apiKey = apiKey
    this.baseUrl = baseUrl
  }

  abstract generate(prompt: string, options?: GenerationOptions): Promise<LLMResponse>
  abstract chat(messages: Array<Message>, options?: GenerationOptions): Promise<LLMResponse>

  /**
   * Helper method to create system message
   */
  protected createSystemMessage(context: string): Message {
    return {
      role: 'system',
      content: `You are an expert career advisor and resume consultant. Your goal is to help users create outstanding, professional CVs that effectively showcase their skills and experience. Be constructive, specific, and encouraging in your feedback.`,
    }
  }

  /**
   * Helper method to validate response
   */
  protected validateResponse(response: LLMResponse): boolean {
    return !!(response.content && response.content.trim().length > 0)
  }
}

/**
 * Mock LLM Service for development/testing
 */
export class MockLLMService extends BaseLLMService {
  readonly name = 'mock'

  constructor() {
    super('mock-key', 'http://localhost')
  }

  async generate(_prompt: string, _options?: GenerationOptions): Promise<LLMResponse> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 500))
    
    return {
      content: '[Mock Response] This would be generated by an LLM in production.',
      usage: {
        promptTokens: 100,
        completionTokens: 50,
        totalTokens: 150,
      },
    }
  }

  async chat(_messages: Array<Message>, _options?: GenerationOptions): Promise<LLMResponse> {
    return this.generate('')
  }
}

/**
 * OpenAI Service Implementation
 */
export class OpenAILLMService extends BaseLLMService {
  readonly name = 'openai'
  private model: string

  constructor(apiKey: string, model = 'gpt-4o-mini') {
    super(apiKey, 'https://api.openai.com/v1')
    this.model = model
  }

  async generate(prompt: string, options?: GenerationOptions): Promise<LLMResponse> {
    const messages: Array<Message> = [
      this.createSystemMessage('CV analysis and optimization'),
      { role: 'user', content: prompt },
    ]

    return this.chat(messages, options)
  }

  async chat(messages: Array<Message>, options?: GenerationOptions): Promise<LLMResponse> {
    const response = await fetch(`${this.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.model,
        messages: messages.map(m => ({ role: m.role, content: m.content })),
        temperature: options?.temperature ?? 0.7,
        max_tokens: options?.maxTokens ?? 1000,
        top_p: options?.topP ?? 1.0,
      }),
    })

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.statusText}`)
    }

    const data = await response.json() as {
      choices: Array<{
        message: { content: string }
        finish_reason: string
      }>
      usage: {
        prompt_tokens: number
        completion_tokens: number
        total_tokens: number
      }
    }

    return {
      content: data.choices[0]?.message.content || '',
      usage: {
        promptTokens: data.usage.prompt_tokens,
        completionTokens: data.usage.completion_tokens,
        totalTokens: data.usage.total_tokens,
      },
      finishReason: data.choices[0]?.finish_reason as LLMResponse['finishReason'],
    }
  }
}

/**
 * Factory function to create LLM service
 */
export function createLLMService(provider: 'mock' | 'openai', apiKey?: string): LLMProvider {
  switch (provider) {
    case 'openai':
      if (!apiKey) {
        throw new Error('API key required for OpenAI')
      }
      return new OpenAILLMService(apiKey)
    case 'mock':
    default:
      return new MockLLMService()
  }
}

// Export singleton (use mock by default)
export const llmService = createLLMService('mock')
